### ISSUE TITLE
PacketIO tries to log packets it didn't read, crashes

### ISSUE THREAD

**Issue by fluut** [thomas-crane/nrelay#13]
nrelay version: `7.5.2`
RotMG version: `X28.0.3`

The issue is caused by the packet.type call in the log at L192, can be solved by placing it right below the actual packet read (as the packet is checked for null there, meanwhile it is not in the current place)

**Comment by thomas-crane** [comment]
Thanks, this should be fixed in eee9fd05196ac511dbcc9e47ea01fe204a794feb (v7.6.0)
