### ISSUE TITLE
error TS2305: Module

### ISSUE THREAD

**Issue by Metal-Fish** [thomas-crane/nrelay#20]
### Version info
 + nrelay version: `newest`
 + RotMG version: `31.1.0`

### Plugins
 + Example key notifier plugin
### Steps to reproduce
1. Run gulp command

### Result
```
src\plugins\notifier.ts(1,10): error TS2305: Module '"C:/Users/Someone/Desktop/nrelay-master/src/core/index"' has no exported member 'Log'.
src\plugins\notifier.ts(1,25): error TS2305: Module '"C:/Users/Someone/Desktop/nrelay-master/src/core/index"' has no exported member 'NrPlugin'.
src\plugins\notifier.ts(1,35): error TS2305: Module '"C:/Users/Someone/Desktop/nrelay-master/src/core/index"' has no exported member 'HookPacket'.
src\plugins\notifier.ts(1,47): error TS2305: Module '"C:/Users/Someone/Desktop/nrelay-master/src/core/index"' has no exported member 'Packet'.
src\plugins\notifier.ts(1,55): error TS2305: Module '"C:/Users/Someone/Desktop/nrelay-master/src/core/index"' has no exported member 'PacketType'.
src\plugins\notifier.ts(1,75): error TS2305: Module '"C:/Users/Someone/Desktop/nrelay-master/src/core/index"' has no exported member 'PluginManager'.
src\plugins\notifier.ts(3,10): error TS2305: Module '"C:/Users/Someone/Desktop/nrelay-master/src/models/server"' has no exported member 'IServer'.
```

**Comment by thomas-crane** [comment]
In commit ce8cb629d3ae31e7bb7a35672bb559b8ea16010a, breaking changes that existed on the dev branch were merged into the master branch.

Based on the errors you're getting it looks like your plugin was last used with version 6.20.0, however the lowest version of nrelay now available is 7.7.1.

The plugin will need to be adjusted in order to work with the latest version of nrelay. To make this process easier, I wrote a [migration guide](https://github.com/thomas-crane/nrelay/blob/master/docs/migration/6-to-7.md) which demonstrates how to update old plugins to the latest syntax.

**Comment by Metal-Fish** [comment]
I went ahead and fixed it, here is the code if you would like to update the discordbot file.

`import { LogLevel, Library, PacketHook, Client } from './../core';
import { Server } from './../models/server';

// If you are missing this run npm install discord.js on the root project directory
import Discord = require('discord.js');

const PORTAL_REGEX = /^{"key":"server.dungeon_opened_by","tokens":{"dungeon":"(\S.*)", "name":"(\w+)"}}$/;

@Library({
    name: 'Notifier - Updated by metal-fish',
    author: 'Lolization',
    enabled: true
})
class KeyNotifier {
    private bot: Discord.Client;
    private ready = false;

    constructor() {
        this.bot = new Discord.Client();
        this.bot.login('YOUR-BOT-KEY');
        this.bot.once('ready', () => this.ready = true);
    }

    callDungeon(name: string, opener: string, server: Server): void {
        if (!this.ready) {
            return;
        }
         // Make sure you have developer settings on in discord otherwise you will not be able to get the channel ID
        // It should be a long string of numbers
        (this.bot.channels.get('channel-ID') as Discord.TextChannel)

        .send(`${name} opened by ${opener} in ${server.name}`)

        .then((msg: Discord.Message) => {
            // msg was successfully sent to discord.
            setTimeout(() => {
                msg.edit(`${msg.content} (closing)`);
            }, 25000); // called after 25 seconds
            setTimeout(() => {
                msg.edit(`${msg.content} (gone)`);
            }, 30000); // called after 30 seconds
        })

        .catch((error: Error) => {
            console.log('Key Notifier', 'An error occurred while sending the message to discord.', LogLevel.Warning);
            console.log('Discord Error', error.message, LogLevel.Error);
        });
    }
}`

**Comment by Metal-Fish** [comment]
Also an unrelated question, is there a guide to connecting the client to realms?
