### ISSUE TITLE
Having an issue starting in console nrelay

### ISSUE THREAD

**Issue by Williaaaaaam** [thomas-crane/nrelay#21]
**Error:**

**

> Your environment has been set up for using Node.js 10.13.0 (x64) and npm.
> 
> C:\Users\x>nrelay
> internal/modules/cjs/loader.js:582
>     throw err;
>     ^
> 
> Error: Cannot find module './dist'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
>     at Module.require (internal/modules/cjs/loader.js:636:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (C:\Users\carmen\nrelay\index.js:3:17)
>     at Module._compile (internal/modules/cjs/loader.js:688:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
>     at Module.load (internal/modules/cjs/loader.js:598:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:529:3)

**

Not sure what I have done wrong, I have done all setup steps, and done the accounts file.

When I attempt to run it in the console (typing nrelay), it pops up with the above error.

I have not setup proxies or local server, not sure if that is required to. But I'll look into doing it sooner or later anyways.

Thanks

**Comment by thomas-crane** [comment]
`dist/` is the folder which is produced when you compile the TypeScript into JavaScript (either by using the command `npm run build`, or the command `gulp`).

The error is happening because the `dist/` folder doesn't exist, so I think the problem is that you might have just missed the "build" step of the setup.

Please try running the command

```bash
npm run build
```

Then try running nrelay again. If that doesn't solve your issue, it could be a problem with nrelay, so please reopen this issue if that is the case.

**Comment by Williaaaaaam** [comment]
When I type that in, it shows up with another error

> $ npm run build
> 
>  nrelay@7.7.1 build C:\Users\x\nrelay
>  gulp
> 
> gulp[2244]: src\node_contextify.cc:628: Assertion `args[1]->IsString()' failed.
>  1: 00007FF64979ECE5
>  2: 00007FF649778196
>  3: 00007FF649778261
>  4: 00007FF64974B56A
>  5: 00007FF649FA2E52
>  6: 00007FF649FA3FD8
>  7: 00007FF649FA330D
>  8: 00007FF649FA322B
>  9: 00000308054DC5C1
> npm ERR! code ELIFECYCLE
> npm ERR! errno 134
> npm ERR! nrelay@7.7.1 build: `gulp`
> npm ERR! Exit status 134
> npm ERR!
> npm ERR! Failed at the nrelay@7.7.1 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\x\AppData\Roaming\npm-cache\_logs\2018-11-24T21_06_36_105Z-debug.log
> 

With the error log showing below: 

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'build' ]
> 2 info using npm@6.4.1
> 3 info using node@v10.13.0
> 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
> 5 info lifecycle nrelay@7.7.1~prebuild: nrelay@7.7.1
> 6 info lifecycle nrelay@7.7.1~build: nrelay@7.7.1
> 7 verbose lifecycle nrelay@7.7.1~build: unsafe-perm in lifecycle true
> 8 verbose lifecycle nrelay@7.7.1~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\x\nrelay\node_modules\.bin;C:\Users\x\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\x\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files\Git\cmd;C:\Program Files (x86)\QuickTime Alternative\QTSystem;C:\Program Files (x86)\Skype\Phone;C:\WINDOWS\System32\OpenSSH;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files\Git\cmd;C:\Program Files (x86)\QuickTime Alternative\QTSystem;C:\Program Files (x86)\Skype\Phone;C:\Users\x\AppData\Local\Programs\Python\Python35\Scripts;C:\Users\x\AppData\Local\Programs\Python\Python35;C:\Users\x\AppData\Local\Microsoft\WindowsApps;C:\ffmpeg\ffmpeg-3.3.1-win64-static\bin;C:\youtube-dl;C:\Users\x\AppData\Local\Microsoft\WindowsApps;C:\Users\x\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
> 9 verbose lifecycle nrelay@7.7.1~build: CWD: C:\Users\x\nrelay
> 10 silly lifecycle nrelay@7.7.1~build: Args: [ '/d /s /c', 'gulp' ]
> 11 silly lifecycle nrelay@7.7.1~build: Returned: code: 134  signal: null
> 12 info lifecycle nrelay@7.7.1~build: Failed to exec build script
> 13 verbose stack Error: nrelay@7.7.1 build: `gulp`
> 13 verbose stack Exit status 134
> 13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
> 13 verbose stack     at EventEmitter.emit (events.js:182:13)
> 13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:182:13)
> 13 verbose stack     at maybeClose (internal/child_process.js:962:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
> 14 verbose pkgid nrelay@7.7.1
> 15 verbose cwd C:\Users\x\nrelay
> 16 verbose Windows_NT 10.0.17134
> 17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
> 18 verbose node v10.13.0
> 19 verbose npm  v6.4.1
> 20 error code ELIFECYCLE
> 21 error errno 134
> 22 error nrelay@7.7.1 build: `gulp`
> 22 error Exit status 134
> 23 error Failed at the nrelay@7.7.1 build script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 134, true ]
> 

Is the command you wanted me to use the same command as gulp? I think it gives me the same error when I use it attempt to make the dist/ folder (got this from the readme.md)

Using gulp gives me the following error too:

> $ gulp
> gulp[1592]: src\node_contextify.cc:628: Assertion `args[1]->IsString()' failed.
>  1: 00007FF64979ECE5
>  2: 00007FF649778196
>  3: 00007FF649778261
>  4: 00007FF64974B56A
>  5: 00007FF649FA2E52
>  6: 00007FF649FA3FD8
>  7: 00007FF649FA330D
>  8: 00007FF649FA322B
>  9: 000002DD097DC5C1
> 

Thanks!

**Comment by thomas-crane** [comment]
This seems to be an issue that isn't specific to nrelay. I did a quick google search for "gulp node contextify assertion failed" and found [this issue on the gulp repository](https://github.com/gulpjs/gulp/issues/2162#issuecomment-384506747) which suggests that the solution is to

+ delete **node_modules** dir and **package-lock.json**.
+ Then run `sudo npm install --unsafe-perm=true`

Since you are using windows, you should use `npm` instead of `sudo npm`.
