### ISSUE TITLE
Can't enter portals in realm

### ISSUE THREAD

**Issue by Maxlaxs** [thomas-crane/nrelay#26]
### Version info
 + nrelay version: `7.7.2`
 + RotMG version: `X31.4.1`

### Plugins
 + Own plugin
    + Uses features
        + stdlib.PlayerTracker
    + Uses packets
        + `UpdatePacket`
        + `NewTickPacket`
        + `MapInfoPacket`
        + `UsePortalPacket`

### Steps to reproduce
1. Start nrelay
2. Go into realm
3. Go into a portal

### Result
```
The bot nexus with the error:
Invalid key used.
```

**Comment by thomas-crane** [comment]
Fixed and tested in 7.7.3
