### ISSUE TITLE
Wasn't sure how to contact anyone for help, so wanted to try here.

### ISSUE THREAD

**Issue by GithubUser201323** [thomas-crane/nrelay#31]
I'm working on creating a plugin for nrelay that involves putting items from the inventory into the vault. I didn't see any packets that allows you to move an item from inventory to chest, or getting an item out of a chest to inventory. Is there any help forum for nrelay, or does anyone know how to do this? 

Thanks

**Comment by dmarcuse** [comment]
IIRC you can use `InvSwapPacket`.

**Comment by GithubUser201323** [comment]
For InvSwapPacket, how would you get the SlotObjectData of the chest?

**Comment by dmarcuse** [comment]
I'm not sure off the top of my head, but it should be present in one of the other packets providing world data.

**Comment by GithubUser201323** [comment]
Ah ok, thank you. I think I got it working, except it isn't actually moving the item. Do you know, does the player need to be over the chest for it to work? I'm trying to do it just from the spawn location in the vault right now.

**Comment by thomas-crane** [comment]
Hi @GithubUser201323 
Yes, the player does have to be standing on top of (or very close to) the vault for the swap to take place.
If you need any further help, or have any more questions, feel free to join the [nrelay discord server](https://discord.gg/yaSRXxh)
