### ISSUE TITLE
Resources being used after connection closed

### ISSUE THREAD

**Issue by zigzag2002** [thomas-crane/nrelay#34]
### Version info
 + nrelay version: `8.4.1`
 + RotMG version: `X31.7.0`

### Plugins
 + Event Notifier
    + Uses packets
        + `UpdatePacket`
        + `ReconnectPacket`

### Steps to reproduce
1. Start nrelay

### Result
```

Resources are being used after the connection has been closed causing things to be undefined

Example:

C:\Users\Administrator\tracker\node_modules\nrelay\lib\core\client.js:453
        const tile = this.mapTiles[y * this.mapInfo.width + x];
                                  ^

TypeError: Cannot read property '33693' of undefined


```

**Comment by thomas-crane** [comment]
I'm almost certain this is issue was fixed in 1f13b6a9d885d903d8f634fb5f232e0bcfdf7dcc but I can't be 100% sure because it was a really rare issue to begin with.

Please reopen this if still experience this issue.

**Comment by thomas-crane** [comment]
Issue is still appearing in 8.5.0

**Comment by zigzag2002** [comment]
I already sent this in discord pm but i guess it's best if i leave it here so its easy to see:
Suggestion is to set this.worldPos to undefined so checkGroundDamage (i think thats the method name) does not get called
