### ISSUE TITLE
unable to npm install and gulp after git clone latest verison(verison 7.8.1) to another computer folder

### ISSUE THREAD

**Issue by batof** [thomas-crane/nrelay#38]
I used verison 6 nrelay since last year, and it run good. 
I noticed there are new verison,
so I git clone latest verison(verison 7.8.1) to another computer folder,
after I npm install instead to the new nrelay verison folder, and gulp,
the cmd shows these error messages:

https://i.imgur.com/72b4xVS.png

Then, I updated my nodejs from verison 8 to 10 , error messages still occur when npm install, gulp

**Comment by batof** [comment]
Fixed? 
https://stackoverflow.com/a/55019685

I fix issue by force install the lodash: npm install --save @types/lodash@4.14.118
It can gulp now

**Comment by thomas-crane** [comment]
This is an issue with gulp. Googling something like "gulp node contextify assertion failed" will yield a lot of results, but in my experience some fixes work and some fixes don't depending on your OS/architecture/etc.

As a side note, if you are just upgrading to a new major version, you might want to check out version 8 of nrelay, which is now [on the dev branch](https://github.com/thomas-crane/nrelay/tree/dev).

Installing version 8 is as simple as

```bash
$ npm install -g nrelay-cli
```

Then you can run

```bash
$ nrelay --help
```

for more info.

Version 8 has a lot of major improvements over v7, and it also doesn't use gulp for builds anymore, which inherently fixes this issue :)
