### ISSUE TITLE
android startup problem

### ISSUE THREAD

**Issue by Mmanks** [thomas-crane/nrelay#8]
android@kali:/opt/nrelay$ nrelay
[23:04:21 | NRelay]           Starting...
[23:04:21 | NRelay]           Checking for updates...
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/opt/nrelay/nrelay-log.log'
Emitted 'error' event at:
    at fs.open (fs.js:2225:12)
    at FSReqWrap.oncomplete (fs.js:153:20)

Help please

**Comment by thomas-crane** [comment]
Looks like the nrelay process doesn't have the right permissions to access the log file. Make sure you are running nrelay as the root user.

If you keep having this problem, you can add the `--no-log` flag to prevent nrelay from writing to the log file. The messages will still appear in the console with this flag.
