### ISSUE TITLE
need help adding names to player tracker

### ISSUE THREAD

**Issue by Mmanks** [thomas-crane/nrelay#9]
i have no clue where and how i add names to the tracker so help please

**Comment by thomas-crane** [comment]
If you are referring to the `player-tracker` plugin, this is not something that you can add names to.

The Player Tracker component is designed to be used as part of other plugins to provide functionality out of the box. Please have a read through the [player tracker docs](https://github.com/thomas-crane/nrelay/blob/master/docs/plugin-components.md#player-tracker) if you would like to know how to utilise the player tracker in your own plugin.
